codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
  # Enable Test Analytics
  test_analytics: true
  # Specify test results file for Test Analytics
  test_results:
    - test-results.xml

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
